version: '3.8'

services:
  app:
    build:
      context: .
      target: runner
    image: 538379554611.dkr.ecr.eu-north-1.amazonaws.com/claude-images-idan-asherov:latest
    env_file:
      - .env
    ports:
      - "8080:3000"
    restart: always